In [3]:
import pandas as pd

In [4]:
import numpy as np

In [5]:
df = pd.read_csv("../data/raw/annual-population-growth/annual-population-growth.csv")

In [6]:
df.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [7]:
df.shape

(38400, 5)

In [8]:
df.columns.tolist()

['Entity',
 'Code',
 'Year',
 'Annual change in population',
 'Annual population change (Projected)']

In [9]:
df.dtypes

Entity                                      str
Code                                        str
Year                                      int64
Annual change in population             float64
Annual population change (Projected)    float64
dtype: object

In [10]:
df.describe()

,Year,Annual change in population,Annual population change (Projected)
count,38400.000000,1.868800e+04,1.971200e+04
mean,2025.500000,2.063019e+06,8.375481e+05
std,43.300872,9.440859e+06,5.816745e+06
min,1951.000000,-3.315935e+06,-2.291035e+07
25%,1988.000000,1.781000e+03,-9.742750e+03
50%,2025.500000,4.689800e+04,9.350000e+01
75%,2063.000000,3.021128e+05,1.411160e+05
max,2100.000000,9.337137e+07,7.206736e+07

In [11]:
df.isnull().sum()

Entity                                      0
Code                                     1200
Year                                        0
Annual change in population             19712
Annual population change (Projected)    18688
dtype: int64

In [12]:
df_year = df[['Year', 'Entity']]
df_year.head()

   Year       Entity
0  1951  Afghanistan
1  1952  Afghanistan
2  1953  Afghanistan
3  1954  Afghanistan
4  1955  Afghanistan

In [13]:
df_2020_mx = df[(df['Year'] == 2020) & (df['Code'] == 'MEX')]
df_2020_mx.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22269,Mexico,MEX,2020,1036075.0,NaN

In [14]:
df_2005_2020_mx = df[(df['Year'] >= 2005) & (df['Year'] <= 2020) & (df['Entity'] == 'Mexico')]
df_2005_2020_mx_final = df_2005_2020_mx[['Entity', 'Year', 'Annual change in population']]
df_2005_2020_mx_final

       Entity  Year  Annual change in population
22254  Mexico  2005                    1417373.0
22255  Mexico  2006                    1442162.0
22256  Mexico  2007                    1520690.0
22257  Mexico  2008                    1599930.0
22258  Mexico  2009                    1625434.0
22259  Mexico  2010                    1624178.0
22260  Mexico  2011                    1619605.0
22261  Mexico  2012                    1574705.0
22262  Mexico  2013                    1525364.0
22263  Mexico  2014                    1440693.0
22264  Mexico  2015                    1288045.0
22265  Mexico  2016                    1179034.0
22266  Mexico  2017                    1148708.0
22267  Mexico  2018                    1173661.0
22268  Mexico  2019                    1189265.0
22269  Mexico  2020                    1036075.0

In [15]:
df_2005_2020_mx_final.mean(numeric_only=True)

Year                              2012.500
Annual change in population    1400307.625
dtype: float64

In [16]:
df.iloc[30:35,0:12]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
30,Afghanistan,AFG,1981,-1231727.0,NaN
31,Afghanistan,AFG,1982,-946206.0,NaN
32,Afghanistan,AFG,1983,-73395.0,NaN
33,Afghanistan,AFG,1984,272237.0,NaN
34,Afghanistan,AFG,1985,236633.0,NaN

In [17]:
df.loc[10000]

Entity                                  Equatorial Guinea
Code                                                  GNQ
Year                                                 2051
Annual change in population                           NaN
Annual population change (Projected)              46407.0
Name: 10000, dtype: object

In [18]:
df.loc[:,["Entity", "Year", "Annual change in population"]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [19]:
df.loc[(df["Entity"] == "Mexico") & (df["Year"] == 2020)]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22269,Mexico,MEX,2020,1036075.0,NaN

In [20]:
df.iloc[0:5, 0:4]

        Entity Code  Year  Annual change in population
0  Afghanistan  AFG  1951                     103163.0
1  Afghanistan  AFG  1952                     108441.0
2  Afghanistan  AFG  1953                     108919.0
3  Afghanistan  AFG  1954                     111251.0
4  Afghanistan  AFG  1955                     119027.0

In [21]:
df.iloc[:, [0,2,3]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [22]:
df_f = df.loc[(df["Year"]>=2005) & (df["Year"]<=2023) & (df["Entity"] == "Afghanistan")]
print(df_f)

         Entity Code  Year  Annual change in population  \
54  Afghanistan  AFG  2005                     843919.0
55  Afghanistan  AFG  2006                    1019525.0
56  Afghanistan  AFG  2007                     485752.0
57  Afghanistan  AFG  2008                     572779.0
58  Afghanistan  AFG  2009                     983471.0
59  Afghanistan  AFG  2010                     817986.0
60  Afghanistan  AFG  2011                    1063620.0
61  Afghanistan  AFG  2012                    1212328.0
62  Afghanistan  AFG  2013                    1062673.0
63  Afghanistan  AFG  2014                    1169819.0
64  Afghanistan  AFG  2015                    1039239.0
65  Afghanistan  AFG  2016                     868846.0
66  Afghanistan  AFG  2017                     988328.0
67  Afghanistan  AFG  2018                    1054099.0
68  Afghanistan  AFG  2019                    1113085.0
69  Afghanistan  AFG  2020                    1212852.0
70  Afghanistan  AFG  2021                     931433.0
71  Afghanistan  AFG  2022                     578437.0
72  Afghanistan  AFG  2023                     875915.0

    Annual population change (Projected)
54                                   NaN
55                                   NaN
56                                   NaN
57                                   NaN
58                                   NaN
59                                   NaN
60                                   NaN
61                                   NaN
62                                   NaN
63                                   NaN
64                                   NaN
65                                   NaN
66                                   NaN
67                                   NaN
68                                   NaN
69                                   NaN
70                                   NaN
71                                   NaN
72                                   NaN

In [26]:
import sys

print("Python", sys.version)
print("Pandas", pd.__version__)
print("NumPy", np.__version__)

Python 3.14.6 (tags/v3.14.6:c63aec6, Jun 10 2026, 10:26:10) [MSC v.1944 64 bit (AMD64)]
Pandas 3.0.5
NumPy 2.5.2